service:
  name: serverless-experiments

plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

custom:
  customDomain:
    domainName: serverless.jeremygreen.me.uk
    stage: production
    certificateName: '*.jeremygreen.me.uk'
    createRoute53Record: false
    endpointType: 'regional'
    securityPolicy: tls_1_2